#!/usr/bin/env python3
"""
Reads Scholarships-detail-page.csv and Scholarships-Information --- 1.xlsx
to generate src/data/scholarshipData.ts with all scholarship data + filter tags.
"""
import csv
import json
import re
import openpyxl

CSV_FILE = "Scholarships-detail-page.csv"
XLSX_FILE = "Scholarships-Information --- 1.xlsx"
OUTPUT_FILE = "src/data/scholarshipData.ts"

# ── Read CSV ──────────────────────────────────────────
scholarships = []
with open(CSV_FILE, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for i, row in enumerate(reader):
        name = (row.get("Name") or "").strip()
        if not name:
            continue
        scholarships.append({
            "id": i + 1,
            "name": name,
            "link": (row.get("Link") or "").strip(),
            "deadline": (row.get("Deadline") or "").strip(),
            "award": (row.get("Award") or "").strip(),
            "eligibility": (row.get("Eligibility") or "").strip(),
            "about": (row.get("About") or "").strip(),
            "detailedEligibility": (row.get("Detailed_Eligibility") or "").strip(),
            "benefits": (row.get("Benefits") or "").strip(),
            "howToApply": (row.get("How_to_Apply") or "").strip(),
        })

print(f"Loaded {len(scholarships)} scholarships from CSV")

# ── Read XLSX filters ────────────────────────────────
# Each sheet name is a filter; scholarships in that sheet belong to that filter
wb = openpyxl.load_workbook(XLSX_FILE, read_only=True)

# Categorize sheets
STATE_SHEETS = ["Maharashtra", "Karnataka", "Gujarat", "Uttar-Pradesh", "Rajasthan", "Madhya-Pradesh", "Bihar", "Telangana"]
CLASS_SHEETS = ["Class(1-10)", "Class(11-12)", "Polytechnic-Diploma-ITI", "Graduation", "Post-Graduation"]
CATEGORY_SHEETS = ["Sports-Talent", "Income-based", "Merit-based", "Cultural-talent", "Visual-Art", "Literary-Art", "Study-Abroad-scholarships-in-In", "International"]

# Build name → filters mapping
name_to_states = {}
name_to_classes = {}
name_to_categories = {}

def normalize(name):
    return name.strip().upper() if name else ""

for sheet_name in wb.sheetnames:
    ws = wb[sheet_name]
    names_in_sheet = set()
    for row in ws.iter_rows(min_row=3, max_col=1, values_only=True):
        n = row[0]
        if n:
            names_in_sheet.add(normalize(n))
    
    # Clean sheet name for display
    display_name = sheet_name.replace("-", " ").replace("(", " ").replace(")", "").strip()
    
    if sheet_name in STATE_SHEETS:
        for n in names_in_sheet:
            name_to_states.setdefault(n, []).append(display_name)
    elif sheet_name in CLASS_SHEETS:
        for n in names_in_sheet:
            name_to_classes.setdefault(n, []).append(display_name)
    elif sheet_name in CATEGORY_SHEETS:
        for n in names_in_sheet:
            name_to_categories.setdefault(n, []).append(display_name)

wb.close()

# ── Merge filters into scholarships ───────────────────
for s in scholarships:
    key = normalize(s["name"])
    s["states"] = sorted(list(set(name_to_states.get(key, []))))
    s["classes"] = sorted(list(set(name_to_classes.get(key, []))))
    s["categories"] = sorted(list(set(name_to_categories.get(key, []))))

# ── Determine primary tag for each scholarship ─────── 
def get_primary_tag(s):
    cats = s["categories"]
    if "Merit based" in cats:
        return "Merit Based"
    if "Income based" in cats:
        return "Means Based"
    if "International" in cats:
        return "International"
    if "Study Abroad scholarships in In" in cats:
        return "Study Abroad"
    if "Sports Talent" in cats:
        return "Sports"
    if "Cultural talent" in cats:
        return "Cultural"
    if "Visual Art" in cats:
        return "Visual Art"
    if "Literary Art" in cats:
        return "Literary Art"
    # Fallback based on eligibility text
    elig = s.get("eligibility", "").lower()
    if "girl" in elig or "female" in elig or "women" in elig:
        return "Girls Scholarship"
    if "class" in elig:
        return "School"
    return "General"

for s in scholarships:
    s["primaryTag"] = get_primary_tag(s)

# ── Generate TypeScript ──────────────────────────────
def escape_ts(val):
    if not val or val == "N/A":
        return ""
    # Escape backticks and ${} for template literals
    val = val.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return val

lines = []
lines.append("// Auto-generated from CSV + XLSX data. Do not edit manually.")
lines.append("// Generated by generate_data.py")
lines.append("")
lines.append("export interface ScholarshipData {")
lines.append("  id: number;")
lines.append("  name: string;")
lines.append("  link: string;")
lines.append("  deadline: string;")
lines.append("  award: string;")
lines.append("  eligibility: string;")
lines.append("  about: string;")
lines.append("  detailedEligibility: string;")
lines.append("  benefits: string;")
lines.append("  howToApply: string;")
lines.append("  primaryTag: string;")
lines.append("  states: string[];")
lines.append("  classes: string[];")
lines.append("  categories: string[];")
lines.append("}")
lines.append("")
lines.append("export const SCHOLARSHIP_DATA: ScholarshipData[] = [")

for s in scholarships:
    lines.append("  {")
    lines.append(f"    id: {s['id']},")
    lines.append(f"    name: `{escape_ts(s['name'])}`,")
    lines.append(f"    link: `{escape_ts(s['link'])}`,")
    lines.append(f"    deadline: `{escape_ts(s['deadline'])}`,")
    lines.append(f"    award: `{escape_ts(s['award'])}`,")
    lines.append(f"    eligibility: `{escape_ts(s['eligibility'])}`,")
    lines.append(f"    about: `{escape_ts(s['about'])}`,")
    lines.append(f"    detailedEligibility: `{escape_ts(s['detailedEligibility'])}`,")
    lines.append(f"    benefits: `{escape_ts(s['benefits'])}`,")
    lines.append(f"    howToApply: `{escape_ts(s['howToApply'])}`,")
    lines.append(f"    primaryTag: `{escape_ts(s['primaryTag'])}`,")
    lines.append(f"    states: {json.dumps(s['states'])},")
    lines.append(f"    classes: {json.dumps(s['classes'])},")
    lines.append(f"    categories: {json.dumps(s['categories'])},")
    lines.append("  },")

lines.append("];")
lines.append("")

# Also export unique filter values
all_tags = sorted(set(s["primaryTag"] for s in scholarships))
all_states_set = sorted(set(st for s in scholarships for st in s["states"]))
all_classes_set = sorted(set(cl for s in scholarships for cl in s["classes"]))
all_categories_set = sorted(set(cat for s in scholarships for cat in s["categories"]))

lines.append(f"export const ALL_TAGS: string[] = {json.dumps(all_tags)};")
lines.append("")
lines.append(f"export const ALL_FILTER_STATES: string[] = {json.dumps(all_states_set)};")
lines.append("")
lines.append(f"export const ALL_FILTER_CLASSES: string[] = {json.dumps(all_classes_set)};")
lines.append("")
lines.append(f"export const ALL_FILTER_CATEGORIES: string[] = {json.dumps(all_categories_set)};")
lines.append("")

with open(OUTPUT_FILE, "w", encoding="utf-8") as out:
    out.write("\n".join(lines))

print(f"Generated {OUTPUT_FILE} with {len(scholarships)} scholarships")
print(f"  Tags: {all_tags}")
print(f"  States: {all_states_set}")
print(f"  Classes: {all_classes_set}")
print(f"  Categories: {all_categories_set}")
